### ISSUE TITLE
charge.js issue

### ISSUE THREAD

**Issue by indraprasetya** [mrkhoa99/Boolfly_payment_fee#1]
Hello

I've been looking for this module for a long time and I try to use your module. But I got problem here.

Uncaught Error: Script error for: Boolfly_PaymentFee/js/view/checkout/summary/charge
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:166)
    at HTMLScriptElement.onScriptError (require.js:1681)
makeError @ require.js:166
onScriptError @ require.js:1681
 
I think you forget to push this file :
'Boolfly_PaymentFee/js/view/checkout/summary/charge'

**Comment by mrkhoa99** [comment]
@indraprasetya thanks you! I'm working on the Front end page now. I'm going to make a pull request at the next weekend!

**Comment by mrkhoa99** [comment]
@indraprasetya now you can download and try this extension again. Welcome any feedback!

**Comment by mrkhoa99** [comment]
@indraprasetya I'm going to close this issue. If having any new issue, please let me know!
