### ISSUE TITLE
PayPal not listed

### ISSUE THREAD

**Issue by miguelcobain** [mrkhoa99/Boolfly_payment_fee#10]
I just set up PayPal method for my store, but that method isn't listed on the select box.
Did anybody experience the same issue?

**Comment by mrkhoa99** [comment]
@miguelcobain you should see:

- https://www.youtube.com/watch?v=e4uOIrfuw5o
- https://developer.paypal.com/developer/accounts/

**Comment by miguelcobain** [comment]
@mrkhoa99 thanks for the response.
However, your links seem to explain how to set up a PayPal sandbox account. That doesn't seem to be my problem.
I have the PayPal payment method correctly configured on a Magento 2 instance. PayPal method appears on the payment methods on checkout.

However, it does not appear on this extensions config, in the methods select box. So, i couldn't set a payment fee for PayPal.
Did you successfully add a payment fee for PayPal with this extension?

There may be multiple ways to set up PayPal with Magento 2. I went with the built in method: Website Payments Standard.

**Comment by mrkhoa99** [comment]
@miguelcobain I will check again and let you know!

**Comment by mrkhoa99** [comment]
Seem that my module works with Payal: https://github.com/mrkhoa99/Boolfly_payment_fee/issues/13.

Can you take some screenshots to show me your config?

**Comment by pointia** [comment]
Any news on how to fix this issue?

**Comment by davidjosephhayes** [comment]
> I have also Problem with Paypal by click the Order Button.
> ![paypal-message](https://user-images.githubusercontent.com/21309911/30918377-a97c307e-a39e-11e7-87c5-26f1f847f8d9.jpg)

https://github.com/mrkhoa99/Boolfly_payment_fee/pull/32

**Comment by mrkhoa99** [comment]
See the fixes from @davidjosephhayes
