### ISSUE TITLE
Setup decimal columns with 10,0 size in sales tables

### ISSUE THREAD

**Issue by JoJuhasz** [mrkhoa99/Boolfly_payment_fee#11]
In Setup/UpgradeShema.php

change lines with:
`
                    '12,4',
`
by:

`
                    'length' => '12,4',
`

**Comment by dvdmierden** [comment]
For me the line said
`'10,2',`

I've changed it to 
`'length' => '10,2',` 
and ran setup:upgrade again .. but I don't know if it had any effect

**Comment by JoJuhasz** [comment]
Oops sorry yes,

change lines with:
`
'10,2',
`
by:
`
'length' => '12,4',
`

**Comment by dvdmierden** [comment]
Confirmed! Thanks for your quick reply!
