### ISSUE TITLE
Rounding issue at checkout

### ISSUE THREAD

**Issue by dvdmierden** [mrkhoa99/Boolfly_payment_fee#12]
In Backoffice at the Payment Fees screen, I've input €2.95 as a payment fee for bank transfer payment method.

In checkout, when selecting the payment method, a fee of €3.00 is calculated. If I change the payment fee to, for example €2.45, it says €2.00 in checkout. It doesn't seem to calculate the decimals of the payment fee.

Sorry for double-posting. Not sure if closed issues (issue #6) appears on any radar

**Comment by JoJuhasz** [comment]
This is directly related to issue #11 
You can change columns details directly in database (by set the lenth of the created columns to 12,4) or delete columns, and run fixed setup.

**Comment by dvdmierden** [comment]
Yes that did it! Thanks for your quick reply
