### ISSUE TITLE
With the Option "Percent" its not correct working

### ISSUE THREAD

**Issue by FloWord** [mrkhoa99/Boolfly_payment_fee#13]
my settings
- 10 percent for payment paypal, if i add product total=69 the calculate +14 fee! For me the correct fee is +6.9

- The second problem, if you calculate the 69 + 14 = 83 but in my store the show me 82.80

Magento: 2.1.7

Any here can help me to fix that?

Backend:
![backend](https://user-images.githubusercontent.com/21309911/28819930-12c6918a-76b0-11e7-8c92-0b492a5f2b3b.JPG)

Frontend:
![frontend](https://user-images.githubusercontent.com/21309911/28819931-12c7e29c-76b0-11e7-895d-43d5a6188a8d.JPG)

**Comment by FloWord** [comment]
Yes PayPal is working but it charged incorrectly with percent. Anybody here how can help?

**Comment by barryvdh** [comment]
Can you try with https://github.com/mrkhoa99/Boolfly_payment_fee/pull/15

Also, the rounding is fixed with #14

**Comment by yhoyoex** [comment]
Boolfly/PaymentFee/Helper/Data.php

public function getFee(\Magento\Quote\Model\Quote $quote) {
        $method  = $quote->getPayment()->getMethod();
        $fee     = $this->methodFee[$method]['fee'];
        $feeType = $this->getFeeType();
        if ($feeType == \Magento\Shipping\Model\Carrier\AbstractCarrier::HANDLING_TYPE_FIXED) {
            return $fee;
        } else {
            // $totals = $quote->getTotals();
            // $sum    = 0;
            // foreach ($totals as $total) {
            //     if ($total->getCode() != self::TOTAL_CODE) {
            //         $sum += (float)$total->getValue();
            //     }
            // }
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $cart = $objectManager->get('\Magento\Checkout\Model\Cart');
            $subTotal = $cart->getQuote()->getSubtotal();
            return ($subTotal * ($fee / 100));
        }
    }

**Comment by davidjosephhayes** [comment]
https://github.com/mrkhoa99/Boolfly_payment_fee/pull/31

**Comment by mrkhoa99** [comment]
See the fixes from @davidjosephhayes
