### ISSUE TITLE
Payment fee not visible in backoffice

### ISSUE THREAD

**Issue by dvdmierden** [mrkhoa99/Boolfly_payment_fee#18]
The payment fee is always zero in the backoffice, even though the grand total includes it in its calculations. We charge €2.95 for the selected payment method.

Subtotal | €7.61
Shipping & Handling | €0.00
Fee Amount | €0.00
Grand Total (Excl.Tax) | €10.13
Tax | €0.43
Grand Total (Incl.Tax) | €10.56

**Comment by dvdmierden** [comment]
On the invoice the payment fee isn't even calculated: 


Subtotal | €7.61
Grand Total (Excl.Tax) | €7.18
Tax | €0.43
Grand Total (Incl.Tax) | €7.61

**Comment by yhoyoex** [comment]
#Boolfly\PaymentFee\Model\Order\Total\Invoice\Fee.php

<?php
namespace Boolfly\PaymentFee\Model\Order\Total\Invoice;

use Magento\Sales\Model\Order\Invoice\Total\AbstractTotal;

class Fee extends AbstractTotal
{
    /**
     * @param \Magento\Sales\Model\Order\Invoice $invoice
     * @return $this
     */
    public function collect(\Magento\Sales\Model\Order\Invoice $invoice)
    {   
        $invoice->setFeeAmount(0);
        $invoice->setBaseFeeAmount(0);
        $amount = $invoice->getOrder()->getFeeAmount();
        $invoice->setFeeAmount($amount);
        $amount = $invoice->getOrder()->getBaseFeeAmount();
        $invoice->setBaseFeeAmount($amount);
        $invoice->setGrandTotal($invoice->getGrandTotal() + $invoice->getFeeAmount());
        $invoice->setBaseGrandTotal($invoice->getBaseGrandTotal() + $invoice->getFeeAmount());
        return $this;
    }
}

**Comment by yogesh-15git** [comment]
@yhoyoex Could you please write the full code of the class:
#Boolfly\PaymentFee\Model\Order\Total\Invoice\Fee.php

**Comment by msliman** [comment]
@yhoyoex Did you get the full code ?

**Comment by yhoyoex** [comment]
that's my full code, it works fine for me

**Comment by yogesh-15git** [comment]
That's cool @yhoyoex

**Comment by yhoyoex** [comment]
I also got the same problem and I solved it by looking at the variable.

Maybe my fee variable is different, look at your variable, I use xdebug to see the variable fee and add it in the class.

**Comment by msliman** [comment]
@yhoyoex Which variable ? please clarify. I am using the this extension without any change

**Comment by yhoyoex** [comment]
@msliman may default ```$invoice->getFeeAmount()``` return false or null

for that I changed the class on #Boolfly_payment_fee/Boolfly/PaymentFee/Observer/AddFeeToOrderObserver.php and #Boolfly_payment_fee/Boolfly/PaymentFee/Helper/ Data.php

**Comment by msliman** [comment]
@yhoyoex Thank you. I fixed it.
What about emails (order and invoice), I am still have no fee value
![fee-email](https://user-images.githubusercontent.com/3694009/36154427-78b4a3b6-10e2-11e8-9b83-2be4d51fe7b2.png)

How can I display them ?

**Comment by yhoyoex** [comment]
@msliman I have never tried to email from magento directly, I use payment gateway to send email to customer.

maybe you just add fee variable to email template.
