### ISSUE TITLE
Compatiblity with Magento 2.2

### ISSUE THREAD

**Issue by vinaykumar9999** [mrkhoa99/Boolfly_payment_fee#20]
Is it Compatible with Magento 2.2 ?

I have installed and tested this but checkout process is not working.

**Comment by mrkhoa99** [comment]
@vinaykumar9999 does not test on Magento 2.2 yet. At this weekends, I will test it and let you know later.

**Comment by samuelecarpene** [comment]
Any news?

**Comment by mrkhoa99** [comment]
@samuelecarpene and @vinaykumar9999 sorry, these days I'm very busy with a project and Merry Christmas. I need time. I'm sure that I will check.

**Comment by vinaykumar9999** [comment]
Hi mrkhoa99. Any news for the update :)

**Comment by GerardPif** [comment]
Not works in magento 2.2r:
[2018-01-24] main.CRITICAL: Notice: unserialize(): Error at offset 0 of 186 bytes in /app/code/Boolfly/PaymentFee/Helper/Data.php on line 40 [] []

Can you help me?

**Comment by GerardPif** [comment]
After change tables and the unserialize error is not working in 2.2.
No errors but fee is always 0.

**Comment by toddhainsworth** [comment]
Note that Magento now provides a SerializerInterface, unserialize is both unsafe and unsupported.
https://github.com/mrkhoa99/Boolfly_payment_fee/pull/27
