### ISSUE TITLE
Dont work on magento 2.2.2

### ISSUE THREAD

**Issue by caww** [mrkhoa99/Boolfly_payment_fee#23]
unserialize error on checkout in data.php line 41

**Comment by caww** [comment]
I feel there more about json than serialize

**Comment by caww** [comment]
Also i found that in my system activated only one paypal system with name paypal_express (as value)
but your module recognized in settings my payment settings as paypal_billing_agreement in value.
Seems this is issue because when i fixed unserialize your module still found no data about my fees because names in settings and in reality is different. 
Hope you will help to fix it

**Comment by FloWord** [comment]
Same with 2.2.3 i can not add products to my cart, its not working. pleas fix that.

**Comment by ird2bcet4cse** [comment]
In 2.2.3 has same isuue with Data.php 
and product does not go to cart

**Comment by giusepperossetti** [comment]
I got the same cart issue but the php error is on line 40 of the data.php file

**Comment by toddhainsworth** [comment]
Magento now provides a SerializerInterface that we should be using rather than manually encoding/decoding data: https://github.com/mrkhoa99/Boolfly_payment_fee/pull/27
