### ISSUE TITLE
Double fee

### ISSUE THREAD

**Issue by ceceghini** [mrkhoa99/Boolfly_payment_fee#24]
In my test shop (test.stampaperfetta.it) I set a € 1 commission on the "Contrassegno" payment method.
On the checkout page I see the commission detail correctly, but in the total it is added twice.
thank's
cesare

**Comment by davidjosephhayes** [comment]
https://github.com/mrkhoa99/Boolfly_payment_fee/pull/32

**Comment by mrkhoa99** [comment]
See the fixes from @davidjosephhayes
