### ISSUE TITLE
Cannot add to cart any product after module install

### ISSUE THREAD

**Issue by giusepperossetti** [mrkhoa99/Boolfly_payment_fee#25]
I installed the module via composer and as soon as I enabled it I can't add to cart any product anymore, responing with a 503 error. Also I got a php error from tha data.php file at line 40.

**Comment by giusepperossetti** [comment]
BTW I'm using Magento CE 2.2.2

**Comment by mrkhoa99** [comment]
@giusepperossetti  Is there any error?

**Comment by giusepperossetti** [comment]
@mrkhoa99 I got 7 JS errors showed in my devtools, you can check this adding to cart a product from the website.
Try adding this product to your cart and check it out!

https://golosopet.it/royal-canin-senior-consult-stage-2-umido-gatto.html

Let me know how can I fix this. Every error showed up just after the module install.

**Comment by chguerra** [comment]
If you edit line 41 in Helper/Data.php and use this line:

`$fees = is_array($initialFees) ? $initialFees : json_decode($initialFees,true);`

It will work

**Comment by toddhainsworth** [comment]
Magento now provides a SerializerInterface that means if they change from JSON to YAML (for example) you don't need to change your logic.

PR implementing this: https://github.com/mrkhoa99/Boolfly_payment_fee/pull/27
