### ISSUE TITLE
How to change the title "Fee Amount"

### ISSUE THREAD

**Issue by tanishmalhotra** [mrkhoa99/Boolfly_payment_fee#34]
I need it to call something else rather than "Fee Amount" on all pages(Checkout, Backend, Invoice, etc). But im a Magento 2 Noob. Need help

Also, in PDF Invoice, it simply adds to the Total without adding a seperate field.

Thanks

**Comment by jwundrak** [comment]
Use a translation .csv (https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/translations/xlate.html)
E.g. `en_US.csv` with
"Fee Amount":"Payment Fee"

@mrkhoa99 Please close. Not an issue
