### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by awwea** [mrkhoa99/Boolfly_payment_fee#4]
Magento 2.1.5
=============
Interception cache generation... 6/7 [========================>---]  85% 35 secs 188.0 MiBErrors during compilation:
        Boolfly\PaymentFee\Block\Adminhtml\System\Form\Field\Methods
                Incorrect dependency in class Boolfly\PaymentFee\Block\Adminhtml\System\Form\Field\Methods in /var/www/MAGENTO/shop/app/code/Boolfly/PaymentFee/Block/Adminhtml/System/Form/Field/Methods.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1

**Comment by mrkhoa99** [comment]
@awwea thanks for reporting! I will check and let you know.

**Comment by mrkhoa99** [comment]
Can you make a pull request?

**Comment by mrkhoa99** [comment]
@awwea I fixed this issue! You should check again and let me know if having any issue.

**Comment by awwea** [comment]
Thank you @mrkhoa99 
confirmed: the fix works
