### ISSUE TITLE
Composer.json

### ISSUE THREAD

**Issue by awwea** [mrkhoa99/Boolfly_payment_fee#5]
https://github.com/awwea/magento2-payment-fee/

I added composer.json to your repo if interested

Best Regards Andre

**Comment by mrkhoa99** [comment]
@awwea yes, you're welcome!

**Comment by mrkhoa99** [comment]
@awwea I think you need to fork my repo > add the composer json to your fork repo > make a pull request.

**Comment by mrkhoa99** [comment]
@awwea  I added the composer json. Thanks!

**Comment by awwea** [comment]
@mrkhoa99 
Please, change the structure of folders too, else won't compile. See example of my fork. Thank You

**Comment by mrkhoa99** [comment]
Yes, thanks! My mistake.
