### ISSUE TITLE
Round

### ISSUE THREAD

**Issue by sopedro** [mrkhoa99/Boolfly_payment_fee#6]
Hi,

Why this extension is rounded the amount of fee? 
if i define 3,5 the amount shows as 4 in cart and if i define 3,2 the amount is shown as 3 in cart but the total are the same, not take the round into account, this is confusing to customer.

Thanks,

Pedro

**Comment by mrkhoa99** [comment]
@sopedro can you take the screenshots and explain more details?

**Comment by mrkhoa99** [comment]
@sopedro I will close the issue after two weeks if not response.

**Comment by dvdmierden** [comment]
This is an issue indeed. In Backoffice at the Payment Fees screen, I've input €2.95 as a payment fee for bank transfer payment method.

In checkout, when selecting the payment method, a fee of €3.00 is calculated. If I change the payment fee to, for example €2.45, it says €2.00 in checkout. It doesn't seem to calculate the decimals of the payment fee.
