### ISSUE TITLE
Tax VAT on fee

### ISSUE THREAD

**Issue by mironsoft75** [mrkhoa99/Boolfly_payment_fee#7]
I do not find any tax on additional fees.
Can you expand that? Or have I overlooked something?

**Comment by mrkhoa99** [comment]
@mironsoft75 I don't expand this part - apply tax on payment fee. Can you have time to investigate on this part and do a pull request?

**Comment by mironsoft75** [comment]
Hi Mr Khoa


I pay 50 EURO if you adjust this to 23.04.2017. I need this urgently.

Vladimir



Am 2017-04-21 11:54, schrieb Mr Khoa:
