### ISSUE TITLE
Hide fee if zero 

### ISSUE THREAD

**Issue by shawkatvirtuos** [mrkhoa99/Boolfly_payment_fee#8]
How can I hide fee , if it is zero, and also I want to show the description as label , is it possible ?

**Comment by JoJuhasz** [comment]
In app/code/Boolfly/PaymentFee/view/frontend/web/js/view/checkout/summary/fee.js
Add:

```
getPureValue: function() {
                var price = 0;
                if (this.totals()) {
                    price = parseFloat(totals.getSegment('fee_amount').value);
                }
                return price;
            },
```

Replace isDisplayed function content by:

`return this.getPureValue() > 0;`


In app/code/Boolfly/PaymentFee/view/frontend/web/template/checkout/summary/fee.html

Replace first line by:

`<!-- ko if: isDisplayed() -->`


In app/code/Boolfly/PaymentFee/view/frontend/web/template/checkout/cart/totals/fee.html

Replace first line by:

`<!-- ko if: isDisplayed() -->`

**Comment by barryvdh** [comment]
FYI, I also removed the isDisplayed() override in  view/frontend/web/js/view/checkout/cart/totals/fee.js so it's also hidden in the totals on the right.
