### ISSUE TITLE
No way to install via composer

### ISSUE THREAD

**Issue by swayoleg** [mrkhoa99/Boolfly_payment_fee#9]
Tried to 

`composer require boolfly/payment-fee`

Got 

>   [InvalidArgumentException]                                                                                                                          
  Could not find package boolfly/payment-fee at any version for your minimum-stability (alpha). Check the package spelling or your minimum-stability  

`composer require boolfly/payment-fee:1.0.0`

Got

> ./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

>  Problem 1
>   - The requested package boolfly/payment-fee could not be found in any version, there may be a typo in the package name.

> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by mrkhoa99** [comment]
See the fixes from @davidjosephhayes
